2023-12-05 11:09:23 - El nombre de usuario ya está en uso
2023-12-05 11:21:41 - Invalid username or passwordorg.springframework.security.authentication.BadCredentialsException: Bad credentials
2023-12-05 11:25:15 - Invalid username or passwordorg.springframework.security.authentication.BadCredentialsException: Bad credentials
2023-12-05 11:25:21 - El nombre de usuario ya está en uso
2023-12-06 23:21:16 - El nombre de usuario ya está en uso
2023-12-06 23:21:23 - El correo ya está en uso
2023-12-07 00:34:54 - No se encontró el rol 'USER'
2023-12-07 00:35:03 - No se encontró el rol 'USER'
2023-12-07 00:35:07 - No se encontró el rol 'USER'
2023-12-07 00:35:09 - No se encontró el rol 'USER'
2023-12-07 00:35:12 - No se encontró el rol 'USER'
2023-12-07 12:43:03 - ErrorCannot invoke "pe.LaCasona.backend_casona.models.Entity.ClienteEntity.getNumeroCompra()" because "cliente" is null
2023-12-07 12:46:13 - ErrorCannot invoke "pe.LaCasona.backend_casona.models.Entity.ClienteEntity.getNumeroCompra()" because "cliente" is null
2023-12-07 12:49:39 - Errororg.hibernate.TransientPropertyValueException: object references an unsaved transient instance - save the transient instance before flushing : pe.LaCasona.backend_casona.models.Entity.DetalleOrdenEntity.orden -> pe.LaCasona.backend_casona.models.Entity.OrdenEntity
